name: vit_dart_extensions
description: Home to useful definitions for dart extensions on basic types.
version: 4.2.0
repository: https://github.com/TimeLord2010/vit_dart_extensions.git

environment:
  sdk: ^3.2.6

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.0
